variables:
  IMAGE: registry.digitwalk.com/lighthouse-node

stages:
  - build
  - push
  - deploy
  - clean

build_staging:
  stage: build
  script:
    - docker build -t $IMAGE:staging .
  only:
    - /^release\/.*$/
    - develop
  tags:
    - build

push_staging:
  stage: push
  script:
    - docker push $IMAGE:staging
  only:
    - /^release\/.*$/
    - develop
  tags:
    - push

deploy_staging:
  stage: deploy
  script:
    - docker-compose -f staging.yml pull
    - docker-compose -f staging.yml run --rm lighthouse_staging env
    - docker-compose -f staging.yml up -d
  only:
    - /^release\/.*$/
    - develop
  tags:
    - staging

cleanup_staging:
  stage: clean
  script:
    - EMPTYIMAGE=$(docker images | awk '{print $1, $3}' | grep '^<none>' | awk '{print $2}') sh -c 'if [ ! -z "$EMPTYIMAGE" ]; then docker rmi $EMPTYIMAGE; fi'
  only:
    - /^release\/.*$/
    - develop
  tags:
    - staging
  allow_failure: true

build_production:
  stage: build
  script:
    - docker build -t $IMAGE:dist .
  only:
    - master
  tags:
    - build

push_production:
  stage: push
  script:
    - docker push $IMAGE:dist
  only:
    - master
  tags:
    - push

deploy_production:
  stage: deploy
  script:
    - docker-compose -f production.yml pull
    - docker-compose -f production.yml run --rm lighthouse_production env
    - docker-compose -f production.yml up -d
  only:
    - master
  tags:
    - production

cleanup_production:
  stage: clean
  script:
    - EMPTYIMAGE=$(docker images | awk '{print $1, $3}' | grep '^<none>' | awk '{print $2}') sh -c 'if [ ! -z "$EMPTYIMAGE" ]; then docker rmi $EMPTYIMAGE; fi'
  only:
    - master
  tags:
    - production
  allow_failure: true
