urlshortener:
  build: .
  ports:
    - "3000:3000"
  environment:
    - VIRTUAL_HOST=urlshortener.docker
  links:
    - mongo:mongo.docker
mongo:
  image: index.alauda.cn/library/mongo
  ports:
    - "27017:27017"
  environment:
    - VIRTUAL_HOST=mongo.docker
