urlshortener_production:
  image: registry.digitwalk.com/url-shortener:dist
  ports:
    - "5038:3000"
  external_links:
    - mongo:mongo
  environment:
    - NODE_ENV=production
    - VIRTUAL_HOST=s.maihoo.com
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
  restart: always
