urlshortener_staging:
  image: registry.digitwalk.com/url-shortener:staging
  ports:
    - "5037:3000"
  external_links:
    - mongo:mongo
  environment:
    - NODE_ENV=staging
    - VIRTUAL_HOST=urlshortener.digitwalk.com
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
  restart: always
